In [90]:
%pip install pandas matplotlib jinja2 xlrd openpyxl

import pandas as pd
import numpy as np
import time

print(f"Pandas version: {pd.__version__}")

Requirement already satisfied: pandas in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (3.0.1)
Requirement already satisfied: matplotlib in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (3.10.8)
Requirement already satisfied: jinja2 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (3.1.6)
Requirement already satisfied: xlrd in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (2.0.2)
Requirement already satisfied: openpyxl in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\smako\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from jinja2) (3.0.3)
Requirement already satisfied: et-xmlfile in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in c:\users\smako\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Pandas version: 3.0.1

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Question 1

In [91]:
energy = pd.read_excel('Energy_Indicators.xls', skiprows=17, skipfooter=38, usecols="C:F")
energy

                    Unnamed: 2 Petajoules Gigajoules           %
0                  Afghanistan        321         10   78.669280
1                      Albania        102         35  100.000000
2                      Algeria       1959         51    0.551010
3               American Samoa        ...        ...    0.641026
4                      Andorra          9        121   88.695650
..                         ...        ...        ...         ...
222                   Viet Nam       2554         28   45.321520
223  Wallis and Futuna Islands          0         26    0.000000
224                      Yemen        344         13    0.000000
225                     Zambia        400         26   99.714670
226                   Zimbabwe        480         32   52.536120

[227 rows x 4 columns]

In [92]:
energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321,10,78.669280
1,Albania,102,35,100.000000
2,Algeria,1959,51,0.551010
3,American Samoa,...,...,0.641026
4,Andorra,9,121,88.695650
...,...,...,...,...
222,Viet Nam,2554,28,45.321520
223,Wallis and Futuna Islands,0,26,0.000000
224,Yemen,344,13,0.000000
225,Zambia,400,26,99.714670
226,Zimbabwe,480,32,52.536120

In [93]:
energy.iloc[:, 1] = pd.to_numeric(energy.iloc[:, 1], errors='coerce')
energy.iloc[:, 1] *= 1000000
energy

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321000000.0,10,78.669280
1,Albania,102000000.0,35,100.000000
2,Algeria,1959000000.0,51,0.551010
3,American Samoa,NaN,...,0.641026
4,Andorra,9000000.0,121,88.695650
...,...,...,...,...
222,Viet Nam,2554000000.0,28,45.321520
223,Wallis and Futuna Islands,0.0,26,0.000000
224,Yemen,344000000.0,13,0.000000
225,Zambia,400000000.0,26,99.714670
226,Zimbabwe,480000000.0,32,52.536120

In [94]:
rename_dict = {
    "Republic of Korea": "South Korea",
    "United States of America": "United States",
    "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"
}

energy["Country"] = energy["Country"].str.replace(r"\(.*?\)", "", regex=True).str.replace(r"\d+", "", regex=True).str.strip()
energy["Country"] = energy["Country"].replace(rename_dict)

energy[energy['Country'].isin(['South Korea', 'United States', 'United Kingdom', 'Hong Kong', 'Bolivia', 'Switzerland', 'Iran'])]

            Country  Energy Supply Energy Supply per Capita  % Renewable
24          Bolivia    336000000.0                       32    31.477120
43        Hong Kong    585000000.0                       82     0.000000
98             Iran   9172000000.0                      119     5.707721
164     South Korea  11007000000.0                      221     2.279353
197     Switzerland   1113000000.0                      136    57.745480
214  United Kingdom   7920000000.0                      124    10.600470
216   United States  90838000000.0                      286    11.570980

In [95]:
GPD = pd.read_csv('world_bank.csv', skiprows=3)
GPD

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.092428e+09,3.276188e+09,3.346623e+09,2.471419e+09,2.880903e+09,3.324034e+09,3.834730e+09,4.265651e+09,NaN,NaN
1,Africa Eastern and Southern,AFE,GDP (current US$),NY.GDP.MKTP.CD,2.420569e+10,2.495889e+10,2.707323e+10,3.176914e+10,3.027955e+10,3.380618e+10,...,9.780765e+11,1.020956e+12,1.018715e+12,9.386076e+11,1.114145e+12,1.228968e+12,1.179359e+12,1.242694e+12,NaN,NaN
2,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.875346e+10,1.805322e+10,1.879944e+10,1.995593e+10,1.426000e+10,1.449724e+10,1.715223e+10,NaN,NaN,NaN
3,Africa Western and Central,AFW,GDP (current US$),NY.GDP.MKTP.CD,1.190481e+10,1.270772e+10,1.363059e+10,1.446891e+10,1.580356e+10,1.692088e+10,...,6.940513e+11,7.778403e+11,1.026996e+12,9.637847e+11,1.026651e+12,1.063649e+12,9.382384e+11,7.363850e+11,NaN,NaN
4,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.437694e+10,8.951279e+10,8.073443e+10,5.885246e+10,7.955954e+10,1.312122e+11,1.071677e+11,1.009989e+11,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.180769e+09,7.878763e+09,7.899741e+09,7.717143e+09,9.413409e+09,9.354908e+09,1.046822e+10,1.119725e+10,NaN,NaN
262,"Yemen, Rep.",YEM,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.684223e+10,2.160616e+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,South Africa,ZAF,GDP (current US$),NY.GDP.MKTP.CD,8.748597e+09,9.225996e+09,9.813996e+09,1.085420e+10,1.195600e+10,1.306899e+10,...,3.814488e+11,4.052607e+11,3.893300e+11,3.379747e+11,4.199863e+11,4.075960e+11,3.814407e+11,4.011450e+11,NaN,NaN
264,Zambia,ZMB,GDP (current US$),NY.GDP.MKTP.CD,6.987397e+08,6.823597e+08,6.792797e+08,7.043397e+08,8.226397e+08,1.061200e+09,...,2.587360e+10,2.631151e+10,2.330867e+10,1.813776e+10,2.209642e+10,2.916378e+10,2.757796e+10,2.530319e+10,NaN,NaN
265,Zimbabwe,ZWE,GDP (current US$),NY.GDP.MKTP.CD,1.053528e+09,1.097207e+09,1.118172e+09,1.160104e+09,1.217759e+09,1.312105e+09,...,5.103566e+10,3.414167e+10,3.335770e+10,3.198033e+10,4.128767e+10,4.075756e+10,3.587178e+10,4.153941e+10,NaN,NaN

In [96]:
rename_dict2 = {
    "Korea, Rep.": "South Korea",
    "Iran, Islamic Rep.": "Iran",
    "Hong Kong SAR, China": "Hong Kong"
}

GPD['Country Name'] = GPD['Country Name'].replace(rename_dict2)
GPD[GPD['Country Name'].isin(['South Korea', 'Iran', 'Hong Kong'])]

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2017,2018,2019,2020,2021,2022,2023,2024,2025,Unnamed: 70
96,Hong Kong,HKG,GDP (current US$),NY.GDP.MKTP.CD,1.320797e+09,1.383682e+09,1.612346e+09,1.935298e+09,2.206466e+09,2.435079e+09,...,3.412733e+11,3.617311e+11,3.630745e+11,3.449431e+11,3.689542e+11,3.586795e+11,3.810430e+11,4.068634e+11,NaN,NaN
112,Iran,IRN,GDP (current US$),NY.GDP.MKTP.CD,4.199134e+09,4.426949e+09,4.693566e+09,4.928628e+09,5.379846e+09,6.197320e+09,...,5.102399e+11,4.119033e+11,3.479884e+11,2.809343e+11,4.073507e+11,4.226623e+11,4.575105e+11,4.752521e+11,NaN,NaN
126,South Korea,KOR,GDP (current US$),NY.GDP.MKTP.CD,3.973069e+09,2.427245e+09,2.826923e+09,4.007692e+09,3.476790e+09,3.141132e+09,...,1.710197e+12,1.824251e+12,1.751046e+12,1.744070e+12,1.942314e+12,1.799363e+12,1.844801e+12,1.875388e+12,NaN,NaN

In [97]:
ScimEn = pd.read_excel('Scimagojr.xlsx')
ScimEn

,Rank,Country,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,Asiatic Region,472465,470142,6591474,4594673,13.95,380
1,2,United States,Northern America,222772,217929,4131736,1119917,18.55,491
2,3,India,Asiatic Region,96975,94714,1243636,479638,12.82,258
3,4,United Kingdom,Western Europe,61946,60287,1326766,207337,21.42,313
4,5,Japan,Asiatic Region,61939,61307,813472,166907,13.13,246
...,...,...,...,...,...,...,...,...,...
209,210,Montserrat,Latin America,1,1,9,0,9.00,1
210,211,Dominica,Latin America,1,1,1,0,1.00,1
211,212,Christmas Island,Pacific Region,1,1,0,0,0.00,0
212,213,Guinea-Bissau,Africa,1,1,55,7,55.00,1
213,214,Marshall Islands,Pacific Region,1,1,1,0,1.00,1

In [98]:
GPD = GPD[["Country Name", "Country Code"] + [str(year) for year in range(2006, 2016)]]
GPD

,Country Name,Country Code,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,Aruba,ABW,2.469783e+09,2.677641e+09,2.843025e+09,2.553793e+09,2.453597e+09,2.637859e+09,2.615208e+09,2.727849e+09,2.790850e+09,2.962907e+09
1,Africa Eastern and Southern,AFE,5.875005e+11,6.749999e+11,7.267704e+11,7.269216e+11,8.638221e+11,9.598225e+11,9.692657e+11,9.813089e+11,9.988362e+11,9.100020e+11
2,Afghanistan,AFG,6.971758e+09,9.747886e+09,1.010930e+10,1.241615e+10,1.585667e+10,1.780510e+10,1.990733e+10,2.014642e+10,2.049713e+10,1.913422e+10
3,Africa Western and Central,AFW,4.020774e+11,4.709476e+11,5.742598e+11,5.150371e+11,6.057943e+11,6.911334e+11,7.480300e+11,8.441804e+11,9.040719e+11,7.780221e+11
4,Angola,AGO,5.865366e+10,7.303782e+10,9.879043e+10,8.170518e+10,9.554692e+10,1.255516e+11,1.435729e+11,1.488452e+11,1.534499e+11,1.025431e+11
...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,NaN,NaN,5.181777e+09,5.015895e+09,5.343951e+09,6.341614e+09,6.163484e+09,6.735329e+09,7.074395e+09,6.295848e+09
262,"Yemen, Rep.",YEM,1.906314e+10,2.165053e+10,2.691086e+10,2.513028e+10,3.090675e+10,3.272642e+10,3.540133e+10,4.041523e+10,4.322859e+10,4.244449e+10
263,South Africa,ZAF,3.038587e+11,3.330771e+11,3.161313e+11,3.297541e+11,4.173638e+11,4.581995e+11,4.344005e+11,4.008860e+11,3.811989e+11,3.467098e+11
264,Zambia,ZMB,1.275686e+10,1.405696e+10,1.791086e+10,1.532834e+10,2.026556e+10,2.345952e+10,2.550306e+10,2.803724e+10,2.714102e+10,2.125122e+10
265,Zimbabwe,ZWE,5.446750e+09,5.294750e+09,4.418000e+09,9.670750e+09,1.204775e+10,1.410900e+10,1.712350e+10,1.910075e+10,1.950550e+10,1.997325e+10

In [99]:
ScimEn = ScimEn[ScimEn["Rank"] <= 15]
ScimEn = ScimEn.rename(columns={"Country": "Country Name"})
ScimEn

,Rank,Country Name,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index
0,1,China,Asiatic Region,472465,470142,6591474,4594673,13.95,380
1,2,United States,Northern America,222772,217929,4131736,1119917,18.55,491
2,3,India,Asiatic Region,96975,94714,1243636,479638,12.82,258
3,4,United Kingdom,Western Europe,61946,60287,1326766,207337,21.42,313
4,5,Japan,Asiatic Region,61939,61307,813472,166907,13.13,246
5,6,Germany,Western Europe,55466,54296,932195,185376,16.81,274
6,7,Russian Federation,Eastern Europe,49938,49562,268391,112125,5.37,123
7,8,Canada,Northern America,44877,44004,1082361,161133,24.12,305
8,9,Italy,Western Europe,42635,40695,767280,171442,18.00,227
9,10,South Korea,Asiatic Region,42534,42174,761076,124789,17.89,215
10,11,Iran,Middle East,35889,35484,798505,211983,22.25,218
11,12,France,Western Europe,33407,32698,637552,99244,19.08,235
12,13,Spain,Western Europe,32521,31781,726414,118758,22.34,233
13,14,Australia,Pacific Region,31047,30232,760284,99637,24.49,262
14,15,Brazil,Latin America,30840,30383,371926,84223,12.06,167

In [100]:
energy = energy.rename(columns={"Country": "Country Name"})
energy

,Country Name,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321000000.0,10,78.669280
1,Albania,102000000.0,35,100.000000
2,Algeria,1959000000.0,51,0.551010
3,American Samoa,NaN,...,0.641026
4,Andorra,9000000.0,121,88.695650
...,...,...,...,...
222,Viet Nam,2554000000.0,28,45.321520
223,Wallis and Futuna Islands,0.0,26,0.000000
224,Yemen,344000000.0,13,0.000000
225,Zambia,400000000.0,26,99.714670
226,Zimbabwe,480000000.0,32,52.536120

In [101]:
merged = pd.merge(ScimEn, energy, how="inner", on="Country Name")
merged = pd.merge(merged, GPD, how="inner", on="Country Name")

In [102]:
print(merged.shape)
merged

(15, 23)

,Rank,Country Name,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
0,1,China,Asiatic Region,472465,470142,6591474,4594673,13.95,380,127191000000.0,...,2.791498e+12,3.604056e+12,4.667346e+12,5.189577e+12,6.192565e+12,7.671757e+12,8.673665e+12,9.743124e+12,1.067453e+13,1.128081e+13
1,2,United States,Northern America,222772,217929,4131736,1119917,18.55,491,90838000000.0,...,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
2,3,India,Asiatic Region,96975,94714,1243636,479638,12.82,258,33195000000.0,...,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
3,4,United Kingdom,Western Europe,61946,60287,1326766,207337,21.42,313,7920000000.0,...,2.719558e+12,3.104700e+12,2.945252e+12,2.429358e+12,2.496741e+12,2.675590e+12,2.719716e+12,2.796908e+12,3.085362e+12,2.945580e+12
4,5,Japan,Asiatic Region,61939,61307,813472,166907,13.13,246,18984000000.0,...,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
5,6,Germany,Western Europe,55466,54296,932195,185376,16.81,274,13261000000.0,...,3.046309e+12,3.484057e+12,3.808198e+12,3.478546e+12,3.467094e+12,3.823576e+12,3.596483e+12,3.807024e+12,3.964871e+12,3.425100e+12
6,7,Russian Federation,Eastern Europe,49938,49562,268391,112125,5.37,123,30709000000.0,...,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
7,8,Canada,Northern America,44877,44004,1082361,161133,24.12,305,10431000000.0,...,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
8,9,Italy,Western Europe,42635,40695,767280,171442,18.00,227,6530000000.0,...,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
9,10,South Korea,Asiatic Region,42534,42174,761076,124789,17.89,215,11007000000.0,...,1.095176e+12,1.220912e+12,1.091581e+12,9.830652e+11,1.192830e+12,1.307103e+12,1.335344e+12,1.434670e+12,1.556252e+12,1.539212e+12
10,11,Iran,Middle East,35889,35484,798505,211983,22.25,218,9172000000.0,...,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
11,12,France,Western Europe,33407,32698,637552,99244,19.08,235,10597000000.0,...,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
12,13,Spain,Western Europe,32521,31781,726414,118758,22.34,233,4923000000.0,...,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
13,14,Australia,Pacific Region,31047,30232,760284,99637,24.49,262,5386000000.0,...,7.497084e+11,8.566036e+11,1.058448e+12,9.317617e+11,1.152567e+12,1.402940e+12,1.552728e+12,1.583737e+12,1.474677e+12,1.356806e+12
14,15,Brazil,Latin America,30840,30383,371926,84223,12.06,167,12149000000.0,...,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

In [103]:
merged = merged.set_index("Country Name")
merged

,Rank,Region,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country Name,,,,,,,,,,,,,,,,,,,,,
China,1,Asiatic Region,472465,470142,6591474,4594673,13.95,380,127191000000.0,93,...,2.791498e+12,3.604056e+12,4.667346e+12,5.189577e+12,6.192565e+12,7.671757e+12,8.673665e+12,9.743124e+12,1.067453e+13,1.128081e+13
United States,2,Northern America,222772,217929,4131736,1119917,18.55,491,90838000000.0,286,...,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,Asiatic Region,96975,94714,1243636,479638,12.82,258,33195000000.0,26,...,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
United Kingdom,4,Western Europe,61946,60287,1326766,207337,21.42,313,7920000000.0,124,...,2.719558e+12,3.104700e+12,2.945252e+12,2.429358e+12,2.496741e+12,2.675590e+12,2.719716e+12,2.796908e+12,3.085362e+12,2.945580e+12
Japan,5,Asiatic Region,61939,61307,813472,166907,13.13,246,18984000000.0,149,...,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
Germany,6,Western Europe,55466,54296,932195,185376,16.81,274,13261000000.0,165,...,3.046309e+12,3.484057e+12,3.808198e+12,3.478546e+12,3.467094e+12,3.823576e+12,3.596483e+12,3.807024e+12,3.964871e+12,3.425100e+12
Russian Federation,7,Eastern Europe,49938,49562,268391,112125,5.37,123,30709000000.0,214,...,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,Northern America,44877,44004,1082361,161133,24.12,305,10431000000.0,296,...,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,Western Europe,42635,40695,767280,171442,18.00,227,6530000000.0,109,...,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
South Korea,10,Asiatic Region,42534,42174,761076,124789,17.89,215,11007000000.0,221,...,1.095176e+12,1.220912e+12,1.091581e+12,9.830652e+11,1.192830e+12,1.307103e+12,1.335344e+12,1.434670e+12,1.556252e+12,1.539212e+12
Iran,11,Middle East,35889,35484,798505,211983,22.25,218,9172000000.0,119,...,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
France,12,Western Europe,33407,32698,637552,99244,19.08,235,10597000000.0,166,...,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
Spain,13,Western Europe,32521,31781,726414,118758,22.34,233,4923000000.0,106,...,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
Australia,14,Pacific Region,31047,30232,760284,99637,24.49,262,5386000000.0,231,...,7.497084e+11,8.566036e+11,1.058448e+12,9.317617e+11,1.152567e+12,1.402940e+12,1.552728e+12,1.583737e+12,1.474677e+12,1.356806e+12
Brazil,15,Latin America,30840,30383,371926,84223,12.06,167,12149000000.0,59,...,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

In [104]:
merged = merged.drop(columns=["Region"])

In [105]:
merged

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country Name,,,,,,,,,,,,,,,,,,,,,
China,1,472465,470142,6591474,4594673,13.95,380,127191000000.0,93,19.754910,...,2.791498e+12,3.604056e+12,4.667346e+12,5.189577e+12,6.192565e+12,7.671757e+12,8.673665e+12,9.743124e+12,1.067453e+13,1.128081e+13
United States,2,222772,217929,4131736,1119917,18.55,491,90838000000.0,286,11.570980,...,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,96975,94714,1243636,479638,12.82,258,33195000000.0,26,14.969080,...,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
United Kingdom,4,61946,60287,1326766,207337,21.42,313,7920000000.0,124,10.600470,...,2.719558e+12,3.104700e+12,2.945252e+12,2.429358e+12,2.496741e+12,2.675590e+12,2.719716e+12,2.796908e+12,3.085362e+12,2.945580e+12
Japan,5,61939,61307,813472,166907,13.13,246,18984000000.0,149,10.232820,...,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
Germany,6,55466,54296,932195,185376,16.81,274,13261000000.0,165,17.901530,...,3.046309e+12,3.484057e+12,3.808198e+12,3.478546e+12,3.467094e+12,3.823576e+12,3.596483e+12,3.807024e+12,3.964871e+12,3.425100e+12
Russian Federation,7,49938,49562,268391,112125,5.37,123,30709000000.0,214,17.288680,...,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,44877,44004,1082361,161133,24.12,305,10431000000.0,296,61.945430,...,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,42635,40695,767280,171442,18.00,227,6530000000.0,109,33.667230,...,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
South Korea,10,42534,42174,761076,124789,17.89,215,11007000000.0,221,2.279353,...,1.095176e+12,1.220912e+12,1.091581e+12,9.830652e+11,1.192830e+12,1.307103e+12,1.335344e+12,1.434670e+12,1.556252e+12,1.539212e+12
Iran,11,35889,35484,798505,211983,22.25,218,9172000000.0,119,5.707721,...,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
France,12,33407,32698,637552,99244,19.08,235,10597000000.0,166,17.020280,...,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
Spain,13,32521,31781,726414,118758,22.34,233,4923000000.0,106,37.968590,...,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
Australia,14,31047,30232,760284,99637,24.49,262,5386000000.0,231,11.810810,...,7.497084e+11,8.566036e+11,1.058448e+12,9.317617e+11,1.152567e+12,1.402940e+12,1.552728e+12,1.583737e+12,1.474677e+12,1.356806e+12
Brazil,15,30840,30383,371926,84223,12.06,167,12149000000.0,59,69.648030,...,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

In [106]:
merged.columns

Index(['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', 'Country Code', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='str')

In [107]:
merged = merged.drop(columns='Country Code')

In [108]:
merged.columns

Index(['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
       'Citations per document', 'H index', 'Energy Supply',
       'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='str')

In [109]:
merged

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country Name,,,,,,,,,,,,,,,,,,,,
China,1,472465,470142,6591474,4594673,13.95,380,127191000000.0,93,19.754910,2.791498e+12,3.604056e+12,4.667346e+12,5.189577e+12,6.192565e+12,7.671757e+12,8.673665e+12,9.743124e+12,1.067453e+13,1.128081e+13
United States,2,222772,217929,4131736,1119917,18.55,491,90838000000.0,286,11.570980,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13
India,3,96975,94714,1243636,479638,12.82,258,33195000000.0,26,14.969080,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
United Kingdom,4,61946,60287,1326766,207337,21.42,313,7920000000.0,124,10.600470,2.719558e+12,3.104700e+12,2.945252e+12,2.429358e+12,2.496741e+12,2.675590e+12,2.719716e+12,2.796908e+12,3.085362e+12,2.945580e+12
Japan,5,61939,61307,813472,166907,13.13,246,18984000000.0,149,10.232820,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
Germany,6,55466,54296,932195,185376,16.81,274,13261000000.0,165,17.901530,3.046309e+12,3.484057e+12,3.808198e+12,3.478546e+12,3.467094e+12,3.823576e+12,3.596483e+12,3.807024e+12,3.964871e+12,3.425100e+12
Russian Federation,7,49938,49562,268391,112125,5.37,123,30709000000.0,214,17.288680,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,44877,44004,1082361,161133,24.12,305,10431000000.0,296,61.945430,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,42635,40695,767280,171442,18.00,227,6530000000.0,109,33.667230,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
South Korea,10,42534,42174,761076,124789,17.89,215,11007000000.0,221,2.279353,1.095176e+12,1.220912e+12,1.091581e+12,9.830652e+11,1.192830e+12,1.307103e+12,1.335344e+12,1.434670e+12,1.556252e+12,1.539212e+12
Iran,11,35889,35484,798505,211983,22.25,218,9172000000.0,119,5.707721,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
France,12,33407,32698,637552,99244,19.08,235,10597000000.0,166,17.020280,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
Spain,13,32521,31781,726414,118758,22.34,233,4923000000.0,106,37.968590,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
Australia,14,31047,30232,760284,99637,24.49,262,5386000000.0,231,11.810810,7.497084e+11,8.566036e+11,1.058448e+12,9.317617e+11,1.152567e+12,1.402940e+12,1.552728e+12,1.583737e+12,1.474677e+12,1.356806e+12
Brazil,15,30840,30383,371926,84223,12.06,167,12149000000.0,59,69.648030,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12

In [120]:
def answer_one():
    return merged

## Question 2

In [123]:
def answer_two():
    Top15 = answer_one()
    years = [str(y) for y in range(2006, 2016)]
    
    avgGDP = Top15[years].mean(axis=1)
    avgGDP.sort_values(ascending=False, inplace=True)
    
    return avgGDP

In [124]:
answer_two()

Country Name
United States         1.570403e+13
China                 7.048894e+12
Japan                 5.239642e+12
Germany               3.590126e+12
United Kingdom        2.791877e+12
France                2.692000e+12
Italy                 2.152983e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.406644e+12
South Korea           1.275614e+12
Australia             1.211998e+12
Iran                  4.567516e+11
dtype: float64

## Question 3

In [125]:
def answer_three():
    Top15 = answer_one()
    avgGDP = answer_two()
    
    sixth_country = avgGDP.index[5]
    
    gdp_change = Top15.loc[sixth_country, '2015'] - Top15.loc[sixth_country, '2006']
    
    return gdp_change

In [127]:
print(answer_three())

124621907951.68018

## Question 4

In [128]:
def answer_four():
    Top15 = answer_one()
    
    Top15['Self-Citation Ratio'] = Top15['Self-citations'] / Top15['Citations']
    
    max_country = Top15['Self-Citation Ratio'].idxmax()
    max_value = Top15['Self-Citation Ratio'].max()
    
    return (max_country, max_value)

In [130]:
print(answer_four())

('China', np.float64(0.6970630544852335))

## Question 5

In [131]:
def answer_five():
    Top15 = answer_one()
    
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    
    Top15_sorted = Top15.sort_values(by='Population', ascending=False)
    
    third_country = Top15_sorted.index[2]
    
    return third_country

In [132]:
print(answer_five())

United States

## Question 6

In [133]:
def answer_six():
    Top15 = answer_one()
    
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    
    Top15['Citable docs per Capita'] = Top15['Citable documents'] / Top15['Population']
    
    correlation = Top15['Citable docs per Capita'].corr(Top15['Energy Supply per Capita'])
    
    return correlation

In [135]:
print(answer_six())

0.6905473831164103

## Question 7

In [136]:
def answer_seven():
    Top15 = answer_one()
    
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    
    ContinentDict = {
        'China':'Asia',
        'United States':'North America',
        'Japan':'Asia',
        'United Kingdom':'Europe',
        'Russian Federation':'Europe',
        'Canada':'North America',
        'Germany':'Europe',
        'India':'Asia',
        'France':'Europe',
        'South Korea':'Asia',
        'Italy':'Europe',
        'Spain':'Europe',
        'Iran':'Asia',
        'Australia':'Australia',
        'Brazil':'South America'
    }
    
    Top15['Continent'] = Top15.index.map(ContinentDict)
    
    result = Top15.groupby('Continent')['Population'].agg(['size','sum','mean','std'])
    
    return result

In [137]:
answer_seven()

               size               sum              mean           std
Continent
Asia              5   2898666386.6106   579733277.32212  6.790979e+08
Australia         1   23316017.316017   23316017.316017           NaN
Europe            6  457929667.216372   76321611.202729  3.464767e+07
North America     2   352855249.48025  176427624.740125  1.996696e+08
South America     1  205915254.237288  205915254.237288           NaN